on:
  push:
    branches: [trunk]
  schedule:
    - cron: "0 0 * * *"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
      - name: Download source
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install UPX
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: upx-ucl
          version: 1.0
      - name: Build Novika
        working-directory: novika
        run: shards build -Dnovika_console -Dnovika_readline --release --no-debug -Dpreview_mt --without-development
      - name: Compress binaries using upx
        working-directory: novika
        run: upx --best bin/nkas bin/novika bin/nki
      - name: Store release directory name in env
        run: export NOVIKA_DIR_NAME=novika-$(git describe --tags)-linux-x86_64
      - name: Create the release directory
        run: mkdir -p $NOVIKA_DIR_NAME/bin
      - name: Copy binaries into the release directory
        working-directory: novika
        run: cp bin/novika bin/nkas bin/nki ../$NOVIKA_DIR_NAME/bin
      - name: Copy environment into the release directory
        working-directory: novika
        run: cp -r env ../$NOVIKA_DIR_NAME/env
      - name: Remove Windows dlls from the environment directory
        working-directory: $NOVIKA_DIR_NAME
        run: rm env/*.dll
      - name: Copy README and LICENSE
        working-directory: $NOVIKA_DIR_NAME
        run: cp ../README.md ../LICENSE .
      - name: Archive the release directory
        run: tar -czf $NOVIKA_DIR_NAME.tar.gz $NOVIKA_DIR_NAME
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: $NOVIKA_DIR_NAME.tar.gz
          path: $NOVIKA_DIR_NAME.tar.gz
