on:
  push:
    branches: [trunk]
  schedule:
    - cron: "0 0 * * *"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
      - name: Download source
        uses: actions/checkout@v3
      - name: Download submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install UPX
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: upx-ucl
          version: 1.0
      - name: Go into the Novika directory
        run: cd novika
      - name: Build Novika
        run: shards build -Dnovika_console -Dnovika_readline --release --no-debug -Dpreview_mt --without-development
      - name: Compress binaries using upx
        run: upx --best bin/nkas bin/novika bin/nki
      - name: Store release directory name in env
        run: export NOVIKA_DIR_NAME=novika-$(git describe --tags)-linux-x86_64
      - name: Create the release directory
        run: mkdir -p ../$NOVIKA_DIR_NAME/bin
      - name: Copy binaries into the release directory
        run: cp bin/novika bin/nkas bin/nki ../$NOVIKA_DIR_NAME/bin
      - name: Copy environment into the release directory
        run: cp -r env ../$NOVIKA_DIR_NAME/env
      - name: Go into the environment directory
        run: cd ../$NOVIKA_DIR_NAME
      - name: Remove Windows dlls from the environment directory
        run: rm env/*.dll
      - name: Copy README and LICENSE
        run: cp ../README.md ../LICENSE .
      - name: Go up
        run: cd ..
      - name: Archive the release directory
        run: tar -czf $NOVIKA_DIR_NAME.tar.gz $NOVIKA_DIR_NAME
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: $NOVIKA_DIR_NAME.tar.gz
          path: $NOVIKA_DIR_NAME.tar.gz
